#+title: Daily work log for Rama Shanbhag

* Month of May
** [2016-05-16 Mon]
   + What is the task I was assigned today?
   I was assigned to follow certain instructions to set up git and emacs on the system.
     And understand the usgae of emacs and git.
   + What did I get done with each task?
   I learnt how to use git along with its various functions and Emacs Text editor along with its various commands.
** [2016-05-17 Tue]
    + What is the task I was assigned today?
   To identify the requirements and design a data model for a web application which has list of users having unique email ID logged in. 
   + What did I get done with each task?
   We identified the actors, entities, their relations with each other and the operations performed on them with the help of state and type structures. 
** [2016-05-18 Wed]
   + What is the task I was assigned today?
   To implement the data model for a web application which has list of users having unique email ID logged in. 
   + What did I get done with each task?
   We implemented certain class along with their operations in python in object oriented approach.
** [2016-05-19 Thu]
   + What is the task I was assigned today?
   Continue with the implementaion of the data model adding session class and its operations
   + What did I get done with each task?
   Implemented a data model with various operations under different classes and formulated various test cases with which the model will be associated.
** [2016-05-20 fri]
   + What is the task I was assigned today?
   Introduce a new class called system and reorganise the operations. Also write the test cases for those operations
   + What did I get done with each task?
   Rewrote code for operations after reorganising them and adding System class. Managed to write test cases for most of the operations and tested them.
   

** Weekly  Summary
   + What are the insights gained?
   Using version controls like git.
   Building a web application, from scratch.
   Using emacs editor.
   Programming with Python.
   Building a data model and an object model for an application.
   + What is my footprint in the realization of the project?
   Getting the hang of building a web application is useful for the project.
** [2016-05-23 Mon]
   + What is the task I was assigned today?
   Start working on ORM, which was the next layer of the application after Object model.
   + What did I get done against each task?
   Understood about the usage of sqlalchemy, flask and other dependencies and installed them on my computer. 
** [2016-05-24 Tue]
   + What is the task I was assigned today?
   Finish writing code for ORM.
   + What did I get done against each task?
   Finished writing code for the ORM.
** [2016-05-25 Wed]
   + What is the task I was assigned today?
   Complete writing test cases for the ORM and Start working on the Rest API.
   + What did I get done against each task?
   Wrote the test cases and got rid of errors in them. Understood the requirements for Rest API.
** [2016-05-26 Thu]
   + What is the task I was assigned today
   Write code for rest API.
   + What did I get done against each task?
   Wrote code for rest API.
** [2016-05-27 Fri]
   + What is the task I was assigned today?
   Complete writing test cases for Rest API and test it. Understand the functionality of front-end with respect to our application.
   + What did I get done against each task?
   Wrote test cases for some methods of rest API and tested them. Also, got a brief idea about front-end of the application.
** Weekly  Summary
   + What are the insights gained?
   How the web application is broken down into key components and how the rest API is built.
   + What is my footprint in the realization of the project?
   Understanding the entire process of building a web application could be considered a pre-requisite for working on the project.
** [2016-05-30 Mon]
   + What is the task I was assigned today?
   Finish testing test cases for rest API and begin working on the front-end.
   + What did I get done against each task?
   Tried to get rid of the numerous errors that were surfacing while running the test cases for rest API.
** [2016-05-31 Tue]
   + What is the task I was assigned today?
   Start working on the front-end of the application.
   + What did I get done against each task?
   Fixed all the errors of rest API and finished writing login logout part of the front-end.

* Month of June
** [2016-06-01 Wed]
   + What is the task I was assigned today?
   Continue working on the front-end of the application.
   + What did I get done against each task?
   Started with front end and added ad user funtionality.
** [2016-06-02 Thu]
   + What is the task I was assigned today?
   Deploy the applications following the steps mentioned by the mentors
   + What did I get done against each task?
   Completed the application by adding funtions like delete and edit user. And deployed this application manually.
** [2016-06-03 Fri]
   + What is the task I was assigned today?
   Present the working of the application with all the test cases running and start with the respective projects
   + What did I get done against each task?
   Could not present due to certain conditions.
** Weekly  Summary
   + What are the insights gained?
   Learnt various concepts related to developemnt of user interface and virtualisation
   + What is my footprint in the realization of the project?
   How the front end of the web application is built and deployed to get a completely working user interface model accessible from every machine.
** [2016-06-06 Mon]
   + What is the task I was assigned today?
   Write test cases for the working all the features of molecular absorption spectroscopy lab. 
   + What did I get done against each task?
   Identified all the test cases and understood the working of all the experiments in this lab
** [2016-06-07 Tue]
   + What is the task I was assigned today?
   Understand certain javascript libraries which might be useful for the project
   + What did I get done against each task?
   Went through the libraries and developed a html static page.
** [2016-06-08 Wed]
   + What is the task I was assigned today?
   Start working on the project and also develop a plugin which helps in installing all the dependencies when the user performs experiments.
   + What did I get done against each task?
   Previously developed HTML page was not responsive. So changed the look and feel of the experiment and made it responsive.
** [2016-06-09 Thu]
   + What is the task I was assigned today?
   Since the user interface of the experiment cannot differ from the original I was asked to redevelop the same thing again
   + What did I get done against each task?
   Using an extractor I extracted all the images from the gitHub file and and started working on them.Since it was getting harder for me to merge all the images extracted I stopped working on for a while to ask for suggestions 
   Also learnt how to develop a plugin and craeted a simple plugin.
** [2016-06-10 Fri]
   + What is the task I was assigned today?
   I was asked to merge all the images in a seperate editor and then use them directly 
   + What did I get done against each task?
   I used Photoshop for creatong diffrent frames and then changing them in a sequesnce so that the object appear to move. 
** Weekly  Summary
   + What are the insights gained?
   + What is my footprint in the realization of the project?
I
   
** [2016-06-13 Mon]
   + What is the task I was assigned today?
   Continue working on the same. Since it was getting complicated I was asked to try out some developer tools to make things simple
   + What did I get done against each task?
   I started looking into createjs, Google createjs toolkit to work directly with javascript. Learnt how to add sprite sheet and building movie clip objects via sprite sheets
* Month of July

