#+title: Daily work log for Rama Shanbhag

* Month of May
** [2016-05-16 Mon]
   + What is the task I was assigned today:
     I was assigned to follow certain instructions to set up git and emacs on the system.
     And understand the usgae of emacs and git.
   + What did I get done with each task:
     I learnt how to use git along with its various functions and Emacs Text editor along with its various commands.
** [2016-05-17 Tue]
   + Task assigned today:
      To identify the requirements and design a data model for a web application which has list of users having unique email ID logged in. 
   + Task we did:
      We identified the actors, entities, their relations with each other and the operations performed on them with the help of state and type structures. 
** [2016-05-18 Wed]
   + Task assigned today:
      To implement the data model for a web application which has list of users having unique email ID logged in. 
   + Task we did:
      We implemented certain class along with their operations in python in object oriented approach.
** [2016-05-19 Thu]
   + Task assigned today:
      Continue with the implementaion of the data model adding session class and its operations
   + Task we did
      Implemented a data model with various operations under different classes and formulated various test cases with which the model will be associated.
** [2016-05-20 fri]
   + Task assigned today:
      Introduce a new class called system and reorganise the operations. Also write the test cases for those operations
   + What did i get done against each task:
      Rewrote code for operations after reorganising them and adding System class. Managed to write test cases for most of the operations and tested them.
   

** Weekly  Summary
   + What are the insights gained?
   Using version controls like git.
   Building a web application, from scratch.
   Using emacs editor.
   Programming with Python.
   Building a data model and an object model for an application.
   + What is my footprint in the realization of the project?
   Getting the hang of building a web application is useful for the project.
** [2016-05-23 Mon]
   + What is the task I was assigned today?
   Start working on ORM, which was the next layer of the application after Object model.
   + What did I get done against each task?
   Understood about the usage of sqlalchemy, flask and other dependencies and installed them on my computer. 
** [2016-05-24 Tue]
   +What is the task I was assigned today?
   Finish writing code for ORM.
   + What did I get done against each task?
   Finished writing code for the ORM.
** [2016-05-25 Wed]
   + What is the task I was assigned today?
   Complete writing test cases for the ORM and Start working on the Rest API.
   + What did I get done against each task?
   Wrote the test cases and got rid of errors in them. Understood the requirements for Rest API.
** [2016-05-26 Thu]
   + What is the task I was assigned today?
   Write code for rest API.
   + What did I get done against each task?
   Wrote code for rest API.
** [2016-05-27 Fri]
   + What is the task I was assigned today?
   Complete writing test cases for Rest API and test it. Understand the functionality of front-end with respect to our application.
   + What did I get done against each task?
   Wrote test cases for some methods of rest API and tested them. Also, got a brief idea about front-end of the application.
** Weekly  Summary
   + What are the insights gained?
   How the web application is broken down into key components and how the rest API is built.
   + What is my footprint in the realization of the project?
   Understanding the entire process of building a web application could be considered a pre-requisite for working on the project.
** [2016-05-30 Mon]
   + What is the task I was assigned today?
   Finish testing test cases for rest API and begin working on the front-end.
   + What did I get done against each task?
   Tried to get rid of the numerous errors that were surfacing while running the test cases for rest API.
** [2016-05-31 Tue]
   + What is the task I was assigned today?
   Start working on the front-end of the application.
   + What did I get done against each task?
   Fixed all the errors of rest API and finished writing login logout part of the front-end.

* Month of June
** [2016-06-01 Wed]
   + What is the task I was assigned today?
   Continue working on the front-end of the application.
   + What did I get done against each task?
   Started with front end and added ad user funtionality.
** [2016-06-02 Thu]
   + What is the task I was assigned today?
   Deploy the applications following the steps mentioned by the mentors
   + What did I get done against each task?
   Completed the application by adding funtions like delete and edit user. And deployed this application manually.
** [2016-06-03 Fri]
   + What is the task I was assigned today?
   Present the working of the application with all the test cases running and start with the reapective projects
   + What did I get done against each task?
   Could not present due to certain conditions.
* Month of July
